# Generated by Django 4.0 on 2024-04-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shoping', '0002_product_descrption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MOB', 'Mobile'), ('LaPTOP', 'Laptop'), ('shitr', 'shirt')], max_length=200),
        ),
    ]
