# Generated by Django 4.2.13 on 2024-06-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profilesetting", "0002_rename_seeprofile_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="profileimg", new_name="image",
        ),
    ]
