# Generated by Django 4.2.13 on 2024-06-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profilesetting", "0003_rename_profileimg_profile_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile", old_name="image", new_name="profileimage",
        ),
    ]
