# Generated by Django 4.2.13 on 2024-06-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profilesetting", "0004_rename_image_profile_profileimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id_user",
            field=models.IntegerField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
