# Generated by Django 4.2.13 on 2024-06-25 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("profilesetting", "0005_alter_profile_id_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="id_user",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
