# Generated by Django 4.2.13 on 2024-06-25 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profilesetting", "0006_alter_profile_id_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 7, 25, 8, 54, 52, 629148, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mobilenumber",
            field=models.IntegerField(default=None, max_length=12),
        ),
    ]
