# Generated by Django 4.2.13 on 2024-06-25 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profilesetting", "0007_alter_profile_dob_alter_profile_mobilenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 7, 25, 8, 57, 3, 410602, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mobilenumber",
            field=models.IntegerField(
                blank=True, default=None, max_length=12, null=True
            ),
        ),
    ]
