# Generated by Django 4.2.13 on 2024-06-30 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profilesetting", "0010_alter_profile_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2024, 7, 30, 15, 51, 21, 590065, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
