# Generated by Django 4.0 on 2024-06-18 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Teacher_img',
        ),
        migrations.AddField(
            model_name='student',
            name='Student_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='education/student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_duration',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_language',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='admition_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='education/subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Teacher_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='education/teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='digree',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='exprence',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='PlacementStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('his_opinion', models.CharField(blank=True, default=None, max_length=3000, null=True)),
                ('his_placement_company', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Education.student')),
            ],
        ),
    ]
