# Generated by Django 4.0 on 2024-06-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_remove_student_teacher_img_student_student_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_alternative_mobile_nnumber',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(blank=True, default=None, max_length=912, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_mobile_nnumber',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Teacher_alternative_mobile_nnumber',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Teacher_email',
            field=models.EmailField(blank=True, default=None, max_length=912, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Teacher_mobile_nnumber',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
