# Generated by Django 4.0 on 2024-06-18 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0003_student_student_alternative_mobile_nnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_icon', models.ImageField(blank=True, default=None, null=True, upload_to='catagoryicon')),
                ('catagory_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('catagory_Descriptin', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='catagory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Education.catagory'),
        ),
    ]
