# Generated by Django 4.0 on 2024-06-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0004_catagory_subject_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
