# Generated by Django 4.0 on 2024-06-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0005_subject_subject_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_syllybas',
            field=models.FileField(blank=True, default=None, null=True, upload_to='education pdf file'),
        ),
    ]
