# Generated by Django 4.2.13 on 2024-06-25 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Education", "0006_subject_subject_syllybas"),
    ]

    operations = [
        migrations.RemoveField(model_name="subject", name="subject_syllybas",),
        migrations.AddField(
            model_name="subject",
            name="PDF",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="education pdf file",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
