# Generated by Django 4.2.13 on 2024-06-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Education", "0007_remove_subject_subject_syllybas_subject_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subject_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ben", "bengoli"),
                    ("hindi", "hindi"),
                    ("English", "English"),
                ],
                default=None,
                max_length=1000,
                null=True,
            ),
        ),
    ]
