# Generated by Django 4.2.13 on 2024-06-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Education", "0008_alter_subject_subject_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="classlanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="subject", name="subject_language",),
        migrations.AddField(
            model_name="subject",
            name="subject_language",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                max_length=1000,
                null=True,
                to="Education.classlanguage",
            ),
        ),
    ]
