# Generated by Django 4.2.13 on 2024-06-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Education", "0009_classlanguage_remove_subject_subject_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="contectme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("mob", models.IntegerField(max_length=13)),
                ("email", models.EmailField(max_length=432)),
                ("message", models.TextField()),
            ],
        ),
    ]
