# Generated by Django 4.2.13 on 2024-07-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Education", "0010_contectme"),
    ]

    operations = [
        migrations.AddField(
            model_name="contectme",
            name="status",
            field=models.CharField(
                choices=[("pending", "pending"), ("accept", "accept")],
                default="pending",
                max_length=50,
            ),
        ),
    ]
