# Generated by Django 4.2.13 on 2024-07-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Education", "0011_contectme_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="subject_language",
            field=models.ManyToManyField(
                blank=True, default=None, null=True, to="Education.classlanguage"
            ),
        ),
    ]
