# Generated by Django 4.0 on 2024-04-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=300)),
                ('movie_descrition', models.TextField()),
                ('movie_upload_time', models.DateTimeField(auto_now_add=True)),
                ('movie_title_image', models.ImageField(upload_to='movieTitle')),
                ('movie_file', models.FileField(null=True, upload_to='movie')),
            ],
        ),
    ]
