# Generated by Django 4.0 on 2024-04-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Action', 'Action'), ('Thriller', 'Thriller'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Western', 'Western'), ('Science fiction', 'Science fiction'), ('Crime film', 'Crime film'), ('Documentary', 'Documentary'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Animation', 'Animation'), ('Adventure', 'Adventure'), ('Experimental', 'Experimental'), ('Historical film', 'Historical film'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Noir', 'Noir'), ('Musical', 'Musical'), ('Television', 'Television'), ('Historical Fiction', 'Historical Fiction'), ('Slasher', 'Slasher'), ('Splatter', 'Splatter'), ('Science fiction', 'Science fiction'), ('Narrative', 'Narrative'), ('Thriller', 'Thriller'), ('Satire', 'Satire'), ('Fantasy', 'Fantasy'), ('Romantic comedy', 'Romantic comedy'), ('History', 'History'), ('War', 'War'), ('Spaghetti western', 'Spaghetti western'), ('LGBT', 'LGBT'), ('Exploitation', 'Exploitation'), ('Apocalyptic and post-apocalyptic fiction', 'Apocalyptic and post-apocalyptic fiction'), ('Blaxploitation', 'Blaxploitation'), ('Sexploitation', 'Sexploitation'), ('Magical Realism', 'Magical Realism'), ('B', 'B'), ('Art', 'Art'), ('abstract animation film', 'abstract animation film'), ('', ''), ('Indie film', 'Indie film'), ('', ''), ('Visual album', 'Visual album'), ('Kaiju', 'Kaiju'), ("Children's film", "Children's film"), ('Animated film', 'Animated film'), ('Punk rock', 'Punk rock'), ('Historical drama', 'Historical drama')], default=0, max_length=103),
        ),
    ]
