# Generated by Django 4.0 on 2024-05-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0004_alter_movie_movie_file_alter_movie_movie_title_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_select',
            field=models.CharField(blank=True, choices=[('trending', 'trending'), ('explore', 'explore'), ('favourite', 'favourite')], default=0, max_length=103),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_catagory_title',
            field=models.CharField(choices=[('poster', 'poster'), ('Popular', 'Popular Movie'), ('New-Movie', 'New Movie'), ('hollywood', 'hollywood Movie'), ('hindi', 'hindi Movie'), ('Bangoli', 'Bangoli Movie'), ('Hindi-Dub', 'Hindi Dub Movie')], default=0, max_length=100),
        ),
    ]
