# Generated by Django 4.0 on 2024-06-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0005_movie_movie_select_alter_movie_movie_catagory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_download_file',
            field=models.URLField(blank=True, default=None, max_length=3000),
        ),
    ]
