# Generated by Django 4.0 on 2024-06-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userragistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(blank=True, default='ba.jpg', null=True, upload_to='profile_images'),
        ),
    ]
